name: Build and check

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    types:
      - opened
      # "synchronize" means new commits pushed to the HEAD of the pull request branch
      - synchronize

permissions: read-all

jobs:
  cancel-previous:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.11.0
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up NODE
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install modules from package-lock.json
        run: npm ci
      - name: Build
        run: npm run build --if-present
